version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx2048m
      GRADLE_OPTS: -Xmx1536m -XX:+HeapDumpOnOutOfMemoryError -Dorg.gradle.caching=true -Dorg.gradle.configureondemand=true -Dkotlin.compiler.execution.strategy=in-process -Dkotlin.incremental=false
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "restaurant-app/base/build.gradle" }}-{{ checksum "user-app/base/build.gradle" }}

      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew

      - run:
          name: Google Services
          command: echo $GOOGLE_SERVICES | base64 --decode > ${HOME}/code/restaurant-app/data/google-services.json

      - run:
          name: API Keys
          command: echo $API_KEYS | base64 --decode > ${HOME}/code/apikey.properties

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "restaurant-app/base/build.gradle" }}-{{ checksum "user-app/base/build.gradle" }}

      - run:
          name: Run Build
          command: ./gradlew lint assembleDebug

      - run:
          name: Run Tests
          command: ./gradlew test
