name: Android CI

on:
  push:
    branches: 
      - 'restaurant*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - name: api key
        run: echo ${{ secrets.API_KEYS }} | base64 --decode > $GITHUB_WORKSPACE/apikey.properties
      
      - name: build
        run: ./gradlew :restaurant-app:assembleDebug
      
      - name: test
        run: ./gradlew :restaurant-app:test
