name: Android CI

on:
  push:
    branches: 
      - 'restaurant*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - name: API keys
        run: echo ${{ secrets.API_KEYS }} | base64 --decode > $GITHUB_WORKSPACE/apikey.properties
      
      - name: Google services
        run: echo ${{ secrets.RESTAURANT_GOOGLE_SERVICES }} | base64 --decode > $GITHUB_WORKSPACE/restaurant-app/data/firebase/google-services.json
      
      - name: build
        run: ./gradlew :restaurant-app:base:assembleDebug
      
      - name: test
        run: ./gradlew :restaurant-app:base:connectedDebugAndroidTest
